### ISSUE TITLE
ORCID as default provider in 3.1.2-branch?

### ISSUE THREAD

**Issue by nmueller18** [leibniz-psychology/openid#10]
Is it planned to integrate ORCID as default provider in the 3.1.2-branch? Such an option seems to be present in the master-branch but misses in the 3.1.2 one.

**Comment by RBoelter** [comment]
You're right, the provider list differs between these two branches. I'll add ORCID to 3.1.2 next week.

**Comment by nmueller18** [comment]
That is great news! I am very much looking forward to it!

**Comment by RBoelter** [comment]
I have added ORCID to 3.1.2-x: https://github.com/leibniz-psychology/openid/releases/tag/v3_1_0-3
It does not have full functionality like the master branch. The login works fine, but the ORCID is automatically set to the user details after the first successful login in the master branch. This doesn't work in 3.1.2 because the implementation is too time consuming for this outdated OJS version.

**Comment by nmueller18** [comment]
Many thanks! I can confirm that the login works fine, and also the linkage between ORCID and an existing account. Unfortunately, the new login overrides our custom login template, and also registering without an ORCID seems no longer possible. I do understand that putting more time into this branch is questionable, so I will try to find a solution myself.

**Comment by RBoelter** [comment]
Unfortunately you are right. I implemented registration without Oauth in OJS 3.3-x (master) version, because the plugin was added to the PKP gallery only for > 3.3-x. The 3.1.2 and 3.2.1 versions of this plugin were created just for our internal OJS systems and therefore some features we don't need are missing.

![Screenshot from 2021-08-06 14-06-24](https://user-images.githubusercontent.com/7657717/128507972-f95357f6-fbc4-43ad-a98f-bb4c74fda5cf.png)
