### ISSUE TITLE
v3_2_0-7 can't Upload A New Plugin

### ISSUE THREAD

**Issue by OhnO395** [leibniz-psychology/openid#11]
![image](https://user-images.githubusercontent.com/3378704/133775448-f9aff0cb-8819-4425-9470-59424c2d01f3.png)

this log error

[php-fpm:access] 127.0.0.1 -  17/Sep/2021:11:22:40 +0000 "POST /index.php?function=upload&category=&plugin=" 500 /app/index.php 90.633 2048 88.27%
[17-Sep-2021 11:22:40] WARNING: [pool www] child 123 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Application::get() in /app/plugins/generic/openid/OpenIDPlugin.inc.php:34"

I use ojs 3.1.2-4
if i can install openid v3_2_0-5.

**Comment by RBoelter** [comment]
the plugin versions v3_2_x_x are not intended for installation in OJS 3.1.x.
I recommend using v3_1_x_x for OJS 3.1.x because as you can see PKP has changed some basic things in OJS 3.2, like:
- OJS 3.1.x
```php
$request = Application::getRequest();
```
- OJS 3.2.x
```php
$request = Application::get()->getRequest();
```
Unfortunately OJS 3.1 is no longer supported by us, therefore [v3_1_0_3](https://github.com/leibniz-psychology/openid/releases/tag/v3_1_0-3) is the last plugin version for OJS 3.1.x..
**Be warned: using an unsupported version may result in lack of features.**

**Comment by OhnO395** [comment]
so sorry i use ojs3.2.1-4
I can install openid v3_2_0-5, but can't install v3_2_0-7

**Comment by RBoelter** [comment]
I'm a little bit confused. 
You write you are using OJS 3.2.1.4 but the version shown in your screenshot is 3.1.2.4 and as I said neither v3_2_0-5 nor v3_2_0-7 are recommended for the version from the screenshot.
It might be possible to install v3_2_0-5 in OJS 3.1.2.4, but as said before this version is for OJS 3.2.x-x

**Comment by OhnO395** [comment]
Oh so  sorry i'm confused.
but i'm test again to ojs3.2.1-4.
I'm sorry

**Comment by OhnO395** [comment]
I'm so sorry.
I'm test in ojs3214 is success.

**Comment by RBoelter** [comment]
No worries. 🙂
