### ISSUE TITLE
When reviewer is selected at registration only Reviewer is assigned, Reader role is not assigned

### ISSUE THREAD

**Issue by gepowy** [leibniz-psychology/openid#17]
When reviewer is selected at registration only Reviewer is assigned, Reader role is not assigned. If user does not select " Yes, I would like to be contacted with requests to review submissions to this journal" then the Reader role is assigned. This occurs even when selecting to register the "register account (without Oauth) so I'm not sure it is a bug in the plugin or normal OJS behavior

**What application are you using?**
 OJS version 3.3.0.8 with plugin after #14

**Comment by RBoelter** [comment]
That should be correct, because a reader role is assigned only if no other role was selected during registration. If I remember correctly, the default OJS registration works the same way. You can test it if you register a user using the normal registration and check the roles of this user. I think there should be no difference.
